name: Publish Packages
run-name: Publish Packages

# Reference: https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/release.yml
on:
  workflow_dispatch:
  push:
    # TODO: this should probably be a release branch or something eh
    # Sequence of patterns matched against refs/tags
    branches: main
  # push:
  #   # Sequence of patterns matched against refs/tags
  #   tags:
  #     - "release-[0-9]+.[0-9]+.[0-9]+*" # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0 or 3.0.0-alpha.
  #       # For more details, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
  #       # and https://docs.npmjs.com/about-semantic-versioning

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish to pnpm
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialize pnpm
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: "Publish to NPM"
        run: pnpm -r publish --no-git-checks --access=public --provenance
